### ISSUE TITLE
Interface feedback

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/SimpleSDMDatasets.jl#4]
Tagging @gabrieldansereau & @gottacatchenall

This is the little experiment I mentioned (maybe only to Gab?), essentially a way to move the code to download raster data out of `SimpleSDMLayers`, for a few different reasons. It's a lot easier to maintain, it has a lot less code re-use, it's a lot safer for users, and it uses types to be smart about a lot more things.

The main change is that pretty much everything in the package now happens thanks to a series of traits (are there layers? can we index the dataset by months? what is the filetype of the things we'll download?) to (i) only download things that exist, and (ii) make it easy to add new datasets.

For example, the entirety of `WorldClim2` (current + future data, not the historical ones) is done in, [according to codecov](https://app.codecov.io/gh/PoisotLab/SimpleSDMDatasets.jl/tree/main/src/providers/WorldClim), about 60 lines -- a lot more in practice but I'm being generous with the whitespace.

I'd really like it if you could take a look at the [documentation](https://poisotlab.github.io/SimpleSDMDatasets.jl/dev/) and give me, essentially, a 👍🏻  or 👎🏻. The next step would be to cut all of the data stuff out of `SimpleSDMLayers`, and replace it by a few calls to this package, to only keep the parts about reading the files and bringing them to the correct format.

This would be a breaking change, but probably one that is easy to justify.

**Comment by gottacatchenall** [comment]
I think the interface makes sense and the docs are clear :+1:

The _aside_ issue I have is that all sources here use the WGS84 coordinate reference systems (CRS) and i think that this https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/issues/32 is (probably) explained because the tiff uses a different CRS.

Not sure it fits into this package, but an easier way for reprojecting tiffs/layers between CRSs (building upon ArchGDAL and Geodesy) would be useful

**Comment by tpoisot** [comment]
I think it's possible to add another trait? Like a string that specifies the CRS? It can be returned by `downloader` as well.

**Comment by tpoisot** [comment]
@gottacatchenall I'm thinking about the best way to implement CRSs. I think an `enum` makes sense, and we can grow it over time? We can start it with `WGS84` as the default, and add CRSs as we need?

**Comment by gottacatchenall** [comment]
@tpoisot I think that makes sense, I think `NAD83` was giving us trouble in the BiaB project so having that would be good. 

I think 
https://github.com/yeesian/ArchGDAL.jl/blob/7b7f559ab6b099298b0b92d675f562bbf5228a8f/src/utilities.jl#L51-L66

is the easiest way to implement the actual transform, unless ArchGDAL has a better way

**Comment by tpoisot** [comment]
I'd rather not do the actual transformation in this package (see the doc for a rationale, it returns a path and metadata), but I agree with the general point -- this will happen SimpleSDMLayers side.

**Comment by tpoisot** [comment]
Just a heads up -- this is going to move to a monorepo with GBIF, Fauxcurrence, and SimpleSDMLayers to make sure everything works together, and take some glue code in the (new) main package.
